### ISSUE TITLE
Alpine-based images

### ISSUE THREAD

**Issue by rochdev** [circleci/circleci-images#158]
It would be nice to have alpine versions of the images. One use case would be when building C/C++ libraries since alpine uses musl instead of glibc. It would also of course be more lightweight.

**Comment by joekohlsdorf** [comment]
CircleCI doesn't provide images for building C/C++.
For services Alpine images are provided.

**Comment by rochdev** [comment]
CircleCI provides Node images, and a Node module may have C/C++ bindings which are compiled during `npm install`.

**Comment by ryanwohara** [comment]
It would be nice but we can't accommodate this request.

**Comment by phawxby** [comment]
@ryanwohara I'd like to add support for this. While it's can't currently be accommodated it probably should be on the roadmap.

We had the exact issues @rochdev described yesterday. We build our node application on CircleCI and deploy to Azure via zip, partly because Azure doesn't support yarn and partly in preparation for boot from zip coming to Linux.

Yesterday we introduced the sharp library and realised when Dev broke that Azure is using Alpine requiring musl. So this brings about two big concerns, first it threw our testing into doubt because it cannot catch this kind of issue (we test for safe application startup and it passed) and second that we cannot build on an environment similar to the one we host on.

So I think this issue should be re-opened. It is an issue and it is something that should be addressed.
