### ISSUE TITLE
Add node version variants from LTS to current

### ISSUE THREAD

**Issue by JakeWharton** [circleci/circleci-images#224]
Right now the only node variant available is 8 which is the current LTS release. However, there is also a 9 and a 10 major version. My project is using features of 10. I would prefer to not have to create a derivative custom image or write the download/install/cache code into my yml. Would you be open to variants of the major version or is that too far out of scope?

**Comment by ryanwohara** [comment]
We only intend to install LTS due to problems we've encountered in the past with newer versions. You're best off extending our non-node variant and installing your version of node on top of it.

Just build it on a schedule with workflows and publish it to your Docker Hub account. 

Extending our images will allow the cache to have most of the image layers around.
