### ISSUE TITLE
OpenJDK7 images?

### ISSUE THREAD

**Issue by jfairley** [circleci/circleci-images#264]
You have a great set of Java images, but unfortunately, my app is stuck on Java7. Would you consider creating a set of Docker images for OpenJDK 7?

**Comment by felicianotech** [comment]
Although our upstream images have OpenJDK 7 the decision for this repo was not to build OpenJDK 7 images because OpenJDK 7/Java 1.7 [has been EOL'd](https://www.oracle.com/technetwork/java/eol-135779.html) and we don't want to build EOL'd software.

@iynere @ryanwohara @marcomorain Do you all have any thoughts on reversing our decision on this? Personally, I agree with not building EOL software. I don't think it should be done. The only reason for consideration for me is that upstream builds it so it's little work for us (longer build times though).

**Comment by felicianotech** [comment]
@iynere Unless you disagree, I'm closing this.
