### ISSUE TITLE
 New images errors with "unable to find user circleci"

### ISSUE THREAD

**Issue by tilgovi** [circleci/circleci-images#275]
Moved from CircleCI-Public/circleci-dockerfiles#17

**Comment by sgerrand** [comment]
Also experiencing this issue. It would be helpful for a step to be added to the CircleCI job that generates these images to try `docker run`ning them after `docker build`.

([migrated](https://github.com/CircleCI-Public/circleci-dockerfiles/issues/17#issuecomment-442198005))

**Comment by Siraris** [comment]
We're experiencing this issue on multiple repo's as well.  We're going to try explicitly setting our docker version using `setup_remote_docker` to see if that resolves it.

**Comment by acburdine** [comment]
Something I noticed while looking at this issue, specifically the `golang` variant of the circleci image, is that the `circleci/golang:1.11.2` image works, while the `circleci/golang:1.11.2-node` image does not. 

Looking at docker hub: 
<img width="913" alt="screen shot 2018-11-27 at 4 04 41 pm" src="https://user-images.githubusercontent.com/5167581/49111466-3253cb00-f25e-11e8-9731-c13897f7a43e.png">

The 1.11.2-node image is 343 MB, while the 1.11.2 image is 438 MB. That doesn't make a lot of sense, since according to [this line](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/golang/images/1.11.2/node/Dockerfile#L9), 1.11.2-node is based off of 1.11.2. It stands to reason that the node image would be larger.

My guess is that the node image might have been built off of `golang:1.11.2` directly rather than `circleci/golang:1.11.2`?

**Comment by coderanger** [comment]
Also affecting the `circleci/python:2.7-stretch-node` image too.

**Comment by acburdine** [comment]
> My guess is that the node image might have been built off of golang:1.11.2 directly rather than circleci/golang:1.11.2?

Running `docker history` on both images seems to confirm this - note that the node variant is missing many of the steps that the non-node variant has:
```
$ docker history circleci/golang:1.11.2
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
1ed987c6aebe        2 hours ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
<missing>           2 hours ago         /bin/sh -c #(nop)  USER [circleci]              0B
<missing>           2 hours ago         /bin/sh -c curl -sSL https://github.com/gote…   3.35MB
<missing>           2 hours ago         /bin/sh -c curl https://raw.githubuserconten…   8.72MB
<missing>           2 hours ago         /bin/sh -c groupadd --gid 3434 circleci   &&…   1.12MB
<missing>           2 hours ago         /bin/sh -c DOCKERIZE_URL="https://circle-dow…   8.53MB
<missing>           2 hours ago         /bin/sh -c COMPOSE_URL="https://circle-downl…   11.7MB
<missing>           2 hours ago         /bin/sh -c set -ex   && export DOCKER_VERSIO…   147MB
<missing>           2 hours ago         /bin/sh -c JQ_URL="https://circle-downloads.…   3.95MB
<missing>           2 hours ago         /bin/sh -c #(nop)  ENV LANG=C.UTF-8             0B
<missing>           2 hours ago         /bin/sh -c locale-gen C.UTF-8 || true           0B
<missing>           2 hours ago         /bin/sh -c ln -sf /usr/share/zoneinfo/Etc/UT…   27B
<missing>           2 hours ago         /bin/sh -c apt-get update   && mkdir -p /usr…   168MB
<missing>           2 hours ago         /bin/sh -c #(nop)  ENV DEBIAN_FRONTEND=nonin…   0B
<missing>           2 hours ago         /bin/sh -c echo 'APT::Get::Assume-Yes "true"…   62B
<missing>           10 days ago         /bin/sh -c #(nop) WORKDIR /go                   0B
<missing>           10 days ago         /bin/sh -c mkdir -p "$GOPATH/src" "$GOPATH/b…   0B
<missing>           10 days ago         /bin/sh -c #(nop)  ENV PATH=/go/bin:/usr/loc…   0B
<missing>           10 days ago         /bin/sh -c #(nop)  ENV GOPATH=/go               0B
<missing>           10 days ago         /bin/sh -c set -eux;   dpkgArch="$(dpkg --pr…   339MB
<missing>           10 days ago         /bin/sh -c #(nop)  ENV GOLANG_VERSION=1.11.2    0B
<missing>           10 days ago         /bin/sh -c apt-get update && apt-get install…   162MB
<missing>           11 days ago         /bin/sh -c apt-get update && apt-get install…   142MB
<missing>           11 days ago         /bin/sh -c set -ex;  if ! command -v gpg > /…   7.81MB
<missing>           11 days ago         /bin/sh -c apt-get update && apt-get install…   23.2MB
<missing>           11 days ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           11 days ago         /bin/sh -c #(nop) ADD file:a61c14b18252183a4…   101MB
```

```
$ docker history circleci/golang:1.11.2-node
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
9cefbd8e0db8        2 hours ago         /bin/sh -c #(nop)  USER [circleci]              0B
<missing>           2 hours ago         /bin/sh -c node --version                       0B
<missing>           2 hours ago         /bin/sh -c set -ex   && for key in     6A010…   5.05MB
<missing>           2 hours ago         /bin/sh -c #(nop)  ENV YARN_VERSION=1.12.3      0B
<missing>           2 hours ago         /bin/sh -c ARCH= && dpkgArch="$(dpkg --print…   54MB
<missing>           2 hours ago         /bin/sh -c #(nop)  ENV NODE_VERSION=8.13.0      0B
<missing>           2 hours ago         /bin/sh -c groupadd --gid 1000 node   && use…   333kB
<missing>           11 days ago         /bin/sh -c set -ex;  apt-get update;  apt-ge…   556MB
<missing>           11 days ago         /bin/sh -c apt-get update && apt-get install…   142MB
<missing>           11 days ago         /bin/sh -c set -ex;  if ! command -v gpg > /…   7.81MB
<missing>           11 days ago         /bin/sh -c apt-get update && apt-get install…   23.2MB
<missing>           11 days ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           11 days ago         /bin/sh -c #(nop) ADD file:a61c14b18252183a4…   101MB
```

**Comment by tilgovi** [comment]
Seems like it's all the `-node` variants, then?

**Comment by acburdine** [comment]
@tilgovi Seems to be that way, yeah. I tested the python-stretch and python-stretch-node images and got the same result.

**Comment by dwtong** [comment]
This is also impacting circleci `elixir-node` images.

**Comment by acburdine** [comment]
This appears to have been fixed. I tested both the golang and python-stretch images since they were pushed late last night.

**Comment by felicianotech** [comment]
Hey,

To provide more information, there was an issue where the `circleci` Linux user wasn't being created in any of the `-node` variant Docker images for our Convenience images. This means that a standard image such as `circleci/golang:1.11` would work but the node variant `circleci/golang:1.11-node` wouldn't.

This issue was found and fix submitted yesterday. By last night/this morning, new images with the fix are published.

Thank you for reporting and your patience.

**Comment by Dombo** [comment]
For anyone who lands here chasing a similar error.

If you're trying to build a multi-stage image with the machine executor, you'll need to load a VM image that has a recent enough Docker version to support it. Otherwise you'll exhibit these same symptoms (multiple FROM clauses causing user not found?)

Easy fix, hope it helps.
