### ISSUE TITLE
Android images node 8 -> 10

### ISSUE THREAD

**Issue by masondaven** [circleci/circleci-images#286]
Is there a reason why all of the android node images (api-*-node8-alpha) were updated to use node 10 instead of 8?

**Comment by ProtoJoe** [comment]
Seconded. The image explicitly states it's Node 8, and @iynere merged changes that set the Node version to 10. Our Android builds are suddenly failing because the Docker image uses the wrong Node version. Please roll back those changes and keep the images accurate.

**Comment by iynere** [comment]
hi there @masondaven @ProtoJoe, we've been publicizing this change since last month:

https://circleci.com/blog/nodejs10-lts
https://discuss.circleci.com/t/convenience-image-node-variants-updated

if you need node 8, i suggest finding an old job from before the change, pulling the image's `sha256` out of the `Spin up Environment` step, and pinning that sha in your config.yml file as decribed in the image README:

https://hub.docker.com/r/circleci/android

**Comment by iynere** [comment]
that said, we should probably change the tag name to reflect the change, so ty @masondaven

**Comment by ProtoJoe** [comment]
Is there a reason you didn't create new images (and point to them as the new defaults moving forward) as opposed to updating the old? Especially given that the Node version is directly in the name of the image?

**Comment by iynere** [comment]
i recommend subscribing to the announcements on discuss : 

https://discuss.circleci.com/c/announcements

and specifically the `convenience-images` tag : 

https://discuss.circleci.com/tags/convenience-images

**Comment by iynere** [comment]
@ProtoJoe it's always been our policy to update images directly rather than simply creating additional versions, with the possibly sole exception of how we handled our recent `-browsers` variant updates (maintaining a `-browsers-legacy` tag)

referencing node 8 specifically in the android images' tags is probably a bug on our part—we shouldn't mention a version at all

**Comment by masondaven** [comment]
Thanks for the help @iynere

**Comment by iynere** [comment]
we'll get this merged into staging & then master https://github.com/circleci/circleci-images/pull/290 @ProtoJoe  @masondaven

**Comment by ProtoJoe** [comment]
Thanks, @iynere. That will reduce confusion moving forward.

**Comment by acristescu** [comment]
> if you need node 8, i suggest finding an old job from before the change, pulling the image's `sha256` out of the `Spin up Environment` step, and pinning that sha in your config.yml file as decribed in the image

How can I find such an image sha digest if I don't have an old job to get it from? Can somebody share one please? :)
