### ISSUE TITLE
clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Mygod** [circleci/circleci-images#430]
Since sometime this past week, android ndk circle CI no longer builds with `circleci/android:api-29-ndk`. The error being `/opt/android/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`.

This change might be due to [PATH changing](https://github.com/CircleCI-Public/circleci-dockerfiles/compare/acc4733...388e1c4#diff-dd542e06e36328276aab6175fac0a513R104) from commit 7e4b53179bbd3eceebe51a2501d2e28f23cff01d.

See an example build: https://circleci.com/gh/shadowsocks/shadowsocks-android/301

**Comment by felicianotech** [comment]
Hey @Mygod,

Thank you for sharing a broken build, that makes this process much easier.

This issue is not because of the PATH change. It's because your build is missing a library, `libtinfo.so.5`. Our Docker Convenience images are dependent on upstream Docker images from the official Docker Library (`hub.docker.com/_/openjdk`).

In this case, upstream decided to update their own base image from Debian 9 "Stretch" to Debian 10 "Buster". Debian 9 includes `libtinfo.o.5` while Debian 10 includes `libtinfo.o.6`. ([ref](https://github.com/docker-library/openjdk/commit/43078a246d7620f518412f458cc689ac869389ac))

There's two possible solutions you can try:

1. `libtinfo.o.6` comes with the Apt package `libtinfo6`. The version you were using has its own package. You can can try installing it at the beginning of your build:

```bash
# Install missing dependency
sudo apt update && sudo apt install -y libtinfo5
```

2. Symlink v6 of the library to v5. This appears to have worked [for someone on a forum](https://forums.xilinx.com/t5/Design-Entry/libtinfo-so-6-instead-of-libtinfo-so-5/td-p/1000106).

```bash
sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5 
```

**Comment by Mygod** [comment]
https://github.com/android-ndk/ndk/issues/574

This seems to be resolved in NDK r18. It is probably a good idea to update NDK version instead.
