### ISSUE TITLE
Ruby 2.7 preview convenience image

### ISSUE THREAD

**Issue by marcotc** [circleci/circleci-images#462]
With the final Ruby 2.7 release coming soon, I'd like to test our project using the latest preview Ruby version.

I noticed that a convenience image for [2.7.0-preview1](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/ruby/images/2.7.0-preview1-stretch) is available, but it has a [breaking bug](https://bugs.ruby-lang.org/issues/15891) that prevents a lot of Ruby programs to run, including any Rails application.

This bug has since been fixed since 2.7.0-preview2, but CircleCI hasn't published new images for 2.7.0-preview2 nor 2.7.0-preview3, both already [available from upstream](https://hub.docker.com/_/ruby/?tab=tags&page=1&name=2.7.0-preview).

Reading the [update schedule](https://circleci.com/blog/build-image-update-schedule/) and [commit history for recently published images](https://github.com/CircleCI-Public/circleci-dockerfiles/commits/master/ruby/images/2.7.0-preview1-stretch), it sounds to me like these images were eligible for automated publishing.

I also looking into the [new generation of convenience images](https://hub.docker.com/r/cimg/ruby), but I couldn't find preview builds available there either. In my case, either current or new generation convenience images would work.

**Comment by felicianotech** [comment]
Looking into this.

**Comment by felicianotech** [comment]
Hi @marcotc,

Apologies for the delay. I discussed this with my team. CircleCI Convenience Images doesn't officially support non-stable releases of the core software in our images. So this means the databases in our service images and languages like Ruby in our language images.

There may be certain exceptions where they slip in and we build them, such as `2.7.0-preview1` as you mentioned. This happens due to the rapidly changing nature of the upstream Docker images and us trying to keep up with their changes.

I have a PR open now for CircleCI Docs in order to make this policy clearer in the future because I agree, this was confusing as to whether we support this or not.

The next-gen images won't be supporting preview/beta/RC releases either. At least for the near future.

## Alternative Solutions

I can think of 2 alternatives here.

1. Build your own custom Docker image with the Ruby version you need. You can use [the Dockerfile](https://github.com/CircleCI-Public/cimg-ruby) from our Next-gen Ruby image as a starting point. Swap a few lines, publish for free to Docker Hub, and you'll have a usable image.
2. A second option would be to use our [Ruby Orb](https://circleci.com/orbs/registry/orb/circleci/ruby). This orb allows you to specify a version of Ruby you'd like to install at runtime and a Apt-based Linux image. If you go this route, here's what this would look like:

```yaml
version: 2.1

orbs:
  ruby: circleci/ruby@0.2

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: 2.7.0-preview3
      - run: |
          ruby --version
```

I hope that helps.
