### ISSUE TITLE
PostgreSQL 9.4.26 is not supported

### ISSUE THREAD

**Issue by davidpgero** [circleci/circleci-images#467]
The last PostgreSQL `9.4.26` is not supported by `postgis/docker-postgis`. 
https://github.com/postgis/docker-postgis/commit/7451856c98cdb343330f8abf9e4c6eb94e1252d0

If I followed it back correctly, the PostgreSQL Circleci image depends on the `postgis/docker-postgis` repository and it does work with `PG > 9.4` now. 

![image](https://user-images.githubusercontent.com/750998/74723492-f75efe00-523a-11ea-922e-0ca20b649bb9.png)

I've just moved back to the `9.4.25` image which works well. The `9.4` PostgreSQL is not supported anymore.

**Comment by felicianotech** [comment]
Hi. Let me try to reword your issue to make sure I understand.

The `circleci/postgres:9.4.26-postgis` image doesn't work for you because the PostGIS install in it is broken while the `circleci/postgres:9.4.25-postgis` image does work for you?

And you found this out because you were using `circleci/postgres:9.4-postgis` which automatically pointed to PostgreSQL v9.4.26 recently and caused your builds to fail?

**Comment by felicianotech** [comment]
It looks like PostgreSQL v9.4 is EOL ([source](https://www.postgresql.org/docs/9.4/release-9-4.html)). Can you see if PostGIS is working fro you in an image with a new version of PostgreSQL?

**Comment by davidpgero** [comment]
:wave: @felicianotech , 

To be more precise, we used `circleci/postgres:9.4-postgis-ram` image to run our test cases. It started to fail 3-4 days ago. At first, it drops a database connection error. After I updated it, we got the `IS_TEMPLATE` syntax error.
![image](https://user-images.githubusercontent.com/750998/74722707-ae5a7a00-5239-11ea-9938-e04e2cae649f.png)

I believe we shouldn't fix this issue because the PostgreSQL `9.4` is EOL as you also said. However, the  `9.24.6` image doesn't work. 
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images/9.4.26

**Comment by felicianotech** [comment]
Great thanks for that info.

Now, the screenshot you just shared is actually a different error than the one in your first post. This new error is actually something I just tracked this morning. You can learn more about that error here: https://discuss.circleci.com/t/postgresql-image-password-not-specified-issue/34555?u=felicianotech

As for trying a newer, I meant can you try a v9.5 or v9.6 image instead of one from the v9.4 series as that series is EOL.

**Comment by davidpgero** [comment]
Oh, this morning I spent my time to figure it out too :D Thank you for summarize and share it!

Anyway, I've set the password as you did in option 1. After that, I got the `IS_TEMPLATE` error. So the pictures that I shared happened in reverse order. 

Currently, we run our product on `9.4` until we update it, we would like to keep the test cases on the `9.4` as well.

**Comment by felicianotech** [comment]
> After that, I got the IS_TEMPLATE error.

Did you get this with a newer version of PostgreSQL (v9.5+)?

Since v9.4 is supported anymore, I see three solutions here.

1. Use an older v9.4 image. You mentioned in your OP that you used `9.4.25` and it worked. So that's a good choice.
2. Switch to a newer, supported release of PostgreSQL.
3. Create your own Docker image to use.

Option 1 is the least amount of work and a stop gap for now. Option 3 is the most amount of work and not something I recommend unless absolutely necessary.

Hopefully this information helps.
