### ISSUE TITLE
Dependencies changing without notice

### ISSUE THREAD

**Issue by aksondhi** [circleci/circleci-images#473]
I ran into an issue where dependencies between a single tagged version (python:2.7.17) changed. Specifically virtualenv was bumped from `16.7.9` to `20.0.7`, a broken release. The issue is not initially apparent since the Dockerfile is using python 2.7.17 as the base image.

I suggest we either maintain some sort of requirements.txt or prevent the overwriting of python image tags in Docker Hub. This way we can ensure a tagged version doesn't have unexpected dependencies change between executions.

**Comment by felicianotech** [comment]
Hi,

Yes this is unfortunately how Convenience Images currently work. Our images are built on top of the upstream official Docker Library images. They recently upgrade the Pip version and they install virtualenv on the fly which will typically pull the latest version. You can see their Dockerfile here: https://github.com/docker-library/python/blob/master/2.7/buster/Dockerfile

We're actually building a next generation fleet of Convenience Images from scratch in order to solve problems like this. Our next-gen Python image exists though it's still in beta. You can find that [here](https://discuss.circleci.com/t/new-python-convenience-image-public-beta/33267?u=felicianotech). You can also see our blog posts on these new images [here](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).
