### ISSUE TITLE
Ruby 2.4 image has Ruby 2.4.1 - should we have 2.4.0?

### ISSUE THREAD

**Issue by keybits** [circleci/circleci-images#51]
Reported here: https://discuss.circleci.com/t/why-circleci-ruby-2-4-installs-ruby-2-4-1/14573

**Comment by DanToml** [comment]
@keybits We mirror the ruby from the upstream docker image so I don't think we have much control over this right now.
Ideally we'd create images with a fully qualified version number, and have x.y point to the latest x.y.z tho.
@zzak probably has more ideas for how to solve the ruby case tho.

**Comment by felicianotech** [comment]
What @DanToml said is exactly how the official Docker Library images work. I think we are doing this.

The reason why we might not have an image tag for `2.4.0` specifically is maybe the official images were created after 2.4.1 was already out?

For all languages in Docker Library, `x.y` points to the most recent version of `x.y.z`. So the issue here is just that we don't have an image for `circleci/ruby:2.4.0`. Why the user wants that though I think is weird, it's a bugfix release so the newer version is better.

**Comment by ryanwohara** [comment]
We don't have any intention to extend images from before this repository exists. An end user can always just use the dockerfile-wizard for a given version:
https://github.com/CircleCI-Public/dockerfile-wizard
