### ISSUE TITLE
Missing postgres 12.2+ (alpine)

### ISSUE THREAD

**Issue by kogkev** [circleci/circleci-images#513]
Looking at the [published](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images) images, (or in [json form](https://circleci.com/docs/2.0/docker-image-tags.json)), we see that starting PostgreSQL [12.2+](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/postgres/images/12.2), there are no more builds for the alpine variant. The latest one seems to be [12.1](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/postgres/images/12.1-alpine/Dockerfile).

I couldn't find any information stating whether this is deliberate, so I'm leaving this message here. Hope to be able to get some CircleCI flavored builds for 12.4 (alpine-ram) so that we our CircleCI workflows can again match production.

Thanks!

**Comment by felicianotech** [comment]
Yes this was intentional. They were dropped 9 months ago: https://github.com/circleci/circleci-images/pull/463

If you really need Alpine, some people have gotten the upstream, non-CircleCI image working. Otherwise, if you are using this as a service image (non-primary image with the Docker executor) than theoretically the images should all behave the same way.

I hope that helps.
