### ISSUE TITLE
Add support for circleci/android:api-31

### ISSUE THREAD

**Issue by agustinsivoplas** [circleci/circleci-images#562]
Can you add support for this android SDK?

**Comment by felicianotech** [comment]
Hi. The image you are referring to here in this repository is the legacy Android image. It's currently in maintenance mode. I'd suggest you use the next-gen Android image instead, which the latest release contains Android API v31.

So instead of trying to do this:

`circleci/android:api-30` or `circleci/android:api-31`

you can do this:

`cimg/android:2021.09.1`.

For the next-gen Android image, the tags are date-based and contain multiple API versions, platform tools, etc. You can find the repository for the image if you are curious, here: https://github.com/CircleCI-Public/cimg-android and also on the [Developer Hub](https://circleci.com/developer/images/image/cimg/android(.
